// sidebars.js
module.exports = {
  docs: [
    {
      type: 'category',
      label: 'I · El incidente',
      className: 'sidebar-icon-zap', // rayo rojo
      collapsed: false,
      items: ['introduccion', 'contexto', 'analisis-incidente', 'reaccion-reposicion'],
    },
    {
      type: 'category',
      label: 'II · Las narrativas',
      className: 'sidebar-icon-compass',
      items: ['analisis-informes', 'impacto-comunicativo'],
    },
    {
      type: 'category',
      label: 'III · Las consecuencias',
      className: 'sidebar-icon-trending',
      items: ['07b-consecuencias-financieras', 'impacto-social', 'resiliencia-futuro'],
    },
    {
      type: 'category',
      label: 'IV · Dimensión europea',
      className: 'sidebar-icon-globe',
      items: [
        'dimension-europea/francia-portugal',
        'dimension-europea/coordinacion-continental',
        'dimension-europea/dia-despues',
      ],
    },
    {
      type: 'category',
      label: 'V · Cierre',
      className: 'sidebar-icon-flag',
      items: ['conclusiones', '08.5-actualizacion-2026', 'uso-ia'],
    },
    {
      type: 'category',
      label: 'Datos en tiempo real',
      className: 'sidebar-icon-activity',
      items: [{ type: 'autogenerated', dirName: 'datos-tiempo-real' }],
    },
    {
      type: 'category',
      label: 'Referencia',
      className: 'sidebar-icon-book',
      items: [
        'resumen-de-cifras',
        'cronologia',
        'anexo-figuras',
        'anexo-tablas',
        'anexo-interactivos',
        'glosario',
        'referencias',
      ],
    },
    'sobre-el-autor',
  ],
};
