// sidebars.js
module.exports = {
  docs: [
    'intro', // landing (slug: /)
    {
      type: 'category',
      label: 'I · El incidente',
      className: 'sidebar-icon-zap', // rayo rojo
      collapsed: false,
      items: ['01-introduccion', '02-contexto', '03-analisis-incidente', '04-reaccion-reposicion'],
    },
    {
      type: 'category',
      label: 'II · Las narrativas',
      className: 'sidebar-icon-compass',
      items: ['05-analisis-informes', '06-impacto-comunicativo'],
    },
    {
      type: 'category',
      label: 'III · Las consecuencias',
      className: 'sidebar-icon-trending',
      items: ['07b-consecuencias-financieras', 'impacto-social', '07-resiliencia-futuro'],
    },
    {
      type: 'category',
      label: 'IV · Dimensión europea',
      className: 'sidebar-icon-globe',
      items: [
        'dimension-europea/01-francia-portugal',
        'dimension-europea/02-coordinacion-continental',
        'dimension-europea/03-dia-despues',
      ],
    },
    {
      type: 'category',
      label: 'V · Cierre',
      className: 'sidebar-icon-flag',
      items: ['09-conclusiones', '08.5-actualizacion-2026', '08-uso-ia'],
    },
    {
      type: 'category',
      label: 'Datos en tiempo real',
      className: 'sidebar-icon-activity',
      items: [{ type: 'autogenerated', dirName: 'datos-tiempo-real' }],
    },
    {
      type: 'category',
      label: 'Referencia',
      className: 'sidebar-icon-book',
      items: [
        '10-resumen-de-cifras',
        '11-cronologia',
        'galeria-graficas',
        '10-galeria-imagenes',
        '15-galeria-de-tablas',
        '16-galeria-forense',
        '15-base-datos-maestra',
        'glosario',
        'referencias',
      ],
    },
    '13-sobre-el-autor',
  ],
};
